-- Tabela ENDERECO
CREATE TABLE ENDERECO (
    COD_END INT PRIMARY KEY NOT NULL,
    LOGRADOURO VARCHAR(40),
    TIPO_LOG VARCHAR(40),
    COMPLEMENTO VARCHAR(20),
    CIDADE VARCHAR(60),
    UF CHAR(1),
    CEP CHAR(8),
    NUMERO VARCHAR(10),
    BAIRRO VARCHAR(60)
);

-- Tabela PROFISSAO
CREATE TABLE PROFISSAO (
    COD_PROF INT PRIMARY KEY NOT NULL,
    NOME VARCHAR(60)
);

-- Tabela CLIENTE
CREATE TABLE CLIENTE (
    COD_CLI INT PRIMARY KEY NOT NULL,
    CPF CHAR(11),
    NOME VARCHAR(60),
    TELEFONE VARCHAR(10),
    COD_PROF INT REFERENCES PROFISSAO(COD_PROF)
);

-- Tabela CLI_ENDERECO
CREATE TABLE CLI_ENDERECO (
    COD_END INT REFERENCES ENDERECO(COD_END),
    COD_CLI INT REFERENCES CLIENTE(COD_CLI),
    PRIMARY KEY (COD_END, COD_CLI)
);

-- Tabela DEPENDENTE
CREATE TABLE DEPENDENTE (
    COD_CLI INT NOT NULL,
    COD_DEP INT NOT NULL,
    PARENTESCO VARCHAR(20),
    PRIMARY KEY (COD_CLI, COD_DEP)
);

-- Tabela CATEGORIA
CREATE TABLE CATEGORIA (
    COD_CAT INT PRIMARY KEY NOT NULL,
    NOME VARCHAR(60),
    VALOR NUMERIC(15,2)
);

-- Tabela GENERO
CREATE TABLE GENERO (
    COD_GEN INT PRIMARY KEY NOT NULL,
    NOME VARCHAR(60)
);

-- Tabela FILMES
CREATE TABLE FILMES (
    COD_FILME INT PRIMARY KEY NOT NULL,
    TITULO_ORIGINAL VARCHAR(100),
    TITULO VARCHAR(100),
    QUANTIDADE INT,
    COD_CAT INT REFERENCES CATEGORIA(COD_CAT),
    COD_GEN INT REFERENCES GENERO(COD_GEN)
);

-- Tabela LOCACAO
CREATE TABLE LOCACAO (
    COD_LOC INT PRIMARY KEY NOT NULL,
    DATA_LOC DATE,
    DESCONTO NUMERIC(15,2),
    MULTA NUMERIC(15,2),
    SUB_TOTAL NUMERIC(15,2),
    COD_CLI INT REFERENCES CLIENTE(COD_CLI)
);

-- Tabela LOCACAO_FILME
CREATE TABLE LOCACAO_FILME (
    COD_LOC INT REFERENCES LOCACAO(COD_LOC),
    COD_FILME INT REFERENCES FILMES(COD_FILME),
    VALOR NUMERIC(15,2),
    NUM_DIAS INT,
    DATA_DEVOL DATE,
    PRIMARY KEY (COD_LOC, COD_FILME)
);

-- Tabela ATOR
CREATE TABLE ATOR (
    COD_ATOR INT PRIMARY KEY NOT NULL,
    NOME VARCHAR(60)
);

-- Tabela FILME_ATOR
CREATE TABLE FILME_ATOR (
    COD_ATOR INT REFERENCES ATOR(COD_ATOR),
    COD_FILME INT REFERENCES FILMES(COD_FILME),
    ATOR CHAR(1),
    DIRETOR CHAR(1),
    PRIMARY KEY (COD_ATOR, COD_FILME)
);

-- Inserir dados de categorias
INSERT INTO CATEGORIA (COD_CAT, NOME, VALOR) VALUES 
(1, 'Terror', 10.00),
(2, 'Romance', 12.00),
(3, 'Drama', 15.00);

-- Inserir dados de gêneros
INSERT INTO GENERO (COD_GEN, NOME) VALUES 
(1, 'Horror'),
(2, 'Romance'),
(3, 'Drama');

-- Inserir dados de filmes

-- Inserir dados na tabela CATEGORIA
INSERT INTO CATEGORIA (COD_CAT, NOME, VALOR) VALUES 
(1, 'Terror', 10.00),
(2, 'Romance', 12.00),
(3, 'Drama', 15.00);


-- Inserir dados na tabela CATEGORIA
INSERT INTO CATEGORIA (COD_CAT, NOME, VALOR) VALUES 
(1, 'Terror', 10.00),
(2, 'Romance', 12.00),
(3, 'Drama', 15.00);

-- Inserir dados na tabela GENERO
INSERT INTO GENERO (COD_GEN, NOME) VALUES 
(1, 'Horror'),
(2, 'Romance'),
(3, 'Drama');

-- Inserir dados na tabela FILMES
INSERT INTO FILMES (COD_FILME, TITULO_ORIGINAL, TITULO, QUANTIDADE, COD_CAT, COD_GEN) VALUES

(1, 'The Conjuring', 'Invocação do Mal', 5, 1, 1),
(2, 'Insidious', 'Sobrenatural', 5, 1, 1),
(3, 'It', 'It - A Coisa', 5, 1, 1),
(4, 'The Ring', 'O Chamado', 5, 1, 1),
(5, 'A Nightmare on Elm Street', 'A Hora do Pesadelo', 5, 1, 1),
(6, 'Pride and Prejudice', 'Orgulho e Preconceito', 5, 2, 2),
(7, 'The Notebook', 'Diário de uma Paixão', 5, 2, 2),
(8, 'La La Land', 'La La Land: Cantando Estações', 5, 2, 2),
(9, 'Titanic', 'Titanic', 5, 2, 2),
(10, 'A Walk to Remember', 'Um Amor para Recordar', 5, 2, 2),
(11, 'The Shawshank Redemption', 'Um Sonho de Liberdade', 5, 3, 3),
(12, 'Forrest Gump', 'Forrest Gump: O Contador de Histórias', 5, 3, 3),
(13, 'Fight Club', 'Clube da Luta', 5, 3, 3),
(14, 'The Godfather', 'O Poderoso Chefão', 5, 3, 3),
(15, 'The Godfather 2', 'O Poderoso Chefão 2', 5, 3, 3)	

SELECT TITULO, TITULO_ORIGINAL, C.NOME AS CATEGORIA, G.NOME AS GENERO
FROM FILMES F
INNER JOIN CATEGORIA C ON F.COD_CAT = C.COD_CAT
INNER JOIN GENERO G ON F.COD_GEN = G.COD_GEN;
